path: /home/danieldrg/Documents/data # Directorio al dataset
train: images/train # Directorio de las imágenes de entrenamiento
val: images/val # Directorio de las imágenes de validación

# Classes
names:
  0: green
  1: red
  2: yellow